#ifndef __whLogin__
#define __whLogin__

/**
@file
Subclass of dlgBaseLogin, which is generated by wxFormBuilder.
*/

#include "dlgBaseLogin.h"

/** Implementing dlgBaseLogin */
class whLogin : public dlgBaseLogin
{
protected:
	// Handlers for dlgBaseLogin events.
	void OnParam( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	whLogin( wxWindow* parent );

	wxString	GetUserName()const	{	return m_cbxUserName->GetValue();	}
	wxString	GetPass()const		{	return m_txtPass->GetValue();		}
	bool		GetStorePass()const	{	return m_chkStorePass->GetValue();	}

	void SetUserName(const wxString& username	)	{	m_cbxUserName->SetValue(username);	}
	void SetPass(const wxString& pass	)			{	m_txtPass->SetValue(pass);			}
	void SetStorePass(bool storepass	)			{	m_chkStorePass->SetValue(storepass);	}
	


};

#endif // __whLogin__
